# Generated by Django 2.0.8 on 2018-08-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recits', '0003_auto_20180820_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recitpage',
            name='date',
        ),
    ]
